/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isu.edu.cs.cs2263.homework_4;
import com.google.common.graph.Graph;
import com.google.common.graph.GraphBuilder;
import com.google.common.graph.Network;
import com.google.common.graph.NetworkBuilder;

public class App {
    public static void main(String args[]) {
        Network<String, Integer > graph = NetworkBuilder.directed().build();

    }
}