/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isu.edu.cs.cs2263.homework_4;
import com.google.common.graph.*;
import javafx.application.Application

public class App {

    public static void main(String args[]) {
        public void start(Stage stage) throws Exception{
            stage.setTitle("Course View");
            stage.show();
        }
        public static void main(String[] args) {
            Application.launch(args);
        }
    }
}